
set -g mouse on
set -sg escape-time 10
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind-key C-k send-keys -R \; clear-history

set -g status-style bg=colour240,fg=white

set -g base-index 1
setw -g pane-base-index 1

# Bind Ctrl-k to clear both the screen and the scrollback buffer
bind -n C-l send-keys C-l \; send-keys -R \; clear-history


# Panel and window titles
#set-option -g allow-rename off
bind-key T command-prompt -p "New pane title:" "select-pane -T '%%'"
set -g pane-border-format " [#{pane_index}] #T "
set -g pane-border-status top
set -g pane-border-style 'fg=blue'
set -g pane-border-lines heavy
set -g pane-active-border-style "fg=magenta"
set -g pane-border-indicators both
set -g pane-scrollbars on
set -g pane-scrollbars-position right
set -g pane-scrollbars-style 'fg=colour244,bg=colour235,width=1,pad=0'

# Enable automatic renumbering when a window is closed
set-option -g renumber-windows on

# Move status bar to the top
set-option -g status-position top

# Fixed width for inactive windows
set-window-option -g window-status-format "#[fg=white,bg=black] #I: #{=30:window_name} "

# Fixed width for the current active window
set-window-option -g window-status-current-format "#[fg=black,bg=blue] #I: #{=30:window_name} "

set -g status-right "#[fg=gray]#(tmux-status.sh)"
set -g status-interval 5



# Move current windows left/right
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Use Alt-number keys to switch windows without prefix
bind-key -n M-0 select-window -t 0
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9


# better style for copying text
set -g copy-mode-match-style 'bg=yellow,fg=black'
set -g copy-mode-current-match-style 'bg=red,fg=white'

# popups
bind-key g display-popup -E -w 90% -h 90% lazygit
bind-key C display-popup -E "$SHELL"


# List of plugins to load
# WARNING:
# remember to execute `. ~/.tmux/plugins/tpm/bin/install_plugins` after 
# changing list of plugins to download/sync files. 
set -g @tpm_plugins '           \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-resurrect  \
'

# Run this once: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Initialize TMUX plugin manager if installed.
if-shell 'test -x "$HOME/.tmux/plugins/tpm/tpm"' 'run-shell "$HOME/.tmux/plugins/tpm/tpm"'
